language: julia
julia:
  - 1.4
addons:
  apt:
    packages:
      - xvfb
jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - xvfb-run julia --project=docs/ docs/make.jl
      after_success: skip
